Install multilib versions of gcc
Otherwise, in `run-length_encoding.c` the `clang -emit-llvm …` step fails with:

```
/usr/include/stdio.h:27:10: fatal error: 'bits/libc-header-start.h' file not found
#include <bits/libc-header-start.h>
```

The missing file belongs to `libc6-dev-i386` but installing the `-multilib` version of gcc is simpler and more fool-proof.